# Exporting Component Description of PFSOC_INIT_MONITOR_C0 to TCL
# Family: PolarFireSoC
# Part Number: MPFS250T_ES-FCVG484E
# Create and Configure the core component PFSOC_INIT_MONITOR_C0
create_and_configure_core -core_vlnv {Microsemi:SgCore:PFSOC_INIT_MONITOR:1.0.307} -component_name {PFSOC_INIT_MONITOR_C0} -params {\
"BANK_0_CALIB_STATUS_ENABLED:true"  \
"BANK_0_CALIB_STATUS_SIMULATION_DELAY:1"  \
"BANK_0_RECALIBRATION_ENABLED:false"  \
"BANK_0_VDDI_STATUS_ENABLED:false"  \
"BANK_0_VDDI_STATUS_SIMULATION_DELAY:1"  \
"BANK_1_CALIB_STATUS_ENABLED:true"  \
"BANK_1_CALIB_STATUS_SIMULATION_DELAY:1"  \
"BANK_1_RECALIBRATION_ENABLED:false"  \
"BANK_1_VDDI_STATUS_ENABLED:false"  \
"BANK_1_VDDI_STATUS_SIMULATION_DELAY:1"  \
"BANK_7_CALIB_STATUS_ENABLED:true"  \
"BANK_7_CALIB_STATUS_SIMULATION_DELAY:1"  \
"BANK_7_RECALIBRATION_ENABLED:false"  \
"BANK_7_VDDI_STATUS_ENABLED:false"  \
"BANK_7_VDDI_STATUS_SIMULATION_DELAY:1"  \
"BANK_8_CALIB_STATUS_ENABLED:true"  \
"BANK_8_CALIB_STATUS_SIMULATION_DELAY:1"  \
"BANK_8_RECALIBRATION_ENABLED:false"  \
"BANK_8_VDDI_STATUS_ENABLED:false"  \
"BANK_8_VDDI_STATUS_SIMULATION_DELAY:1"  \
"BANK_9_CALIB_STATUS_ENABLED:true"  \
"BANK_9_CALIB_STATUS_SIMULATION_DELAY:1"  \
"BANK_9_RECALIBRATION_ENABLED:false"  \
"BANK_9_VDDI_STATUS_ENABLED:false"  \
"BANK_9_VDDI_STATUS_SIMULATION_DELAY:1"  \
"DEVICE_INIT_DONE_SIMULATION_DELAY:12"  \
"FABRIC_DELAY_INCR:3"  \
"FABRIC_POR_N_SIMULATION_DELAY:1"  \
"LATCH_SC_OUTPUTS:false"  \
"PCIE_DELAY_INCR:2"  \
"PCIE_INIT_DONE_SIMULATION_DELAY:4"  \
"SHOW_BANK_0_CALIB_STATUS_ENABLED:true"  \
"SHOW_BANK_0_RECALIBRATION_ENABLED:true"  \
"SHOW_BANK_0_VDDI_STATUS_ENABLED:true"  \
"SHOW_BANK_1_CALIB_STATUS_ENABLED:true"  \
"SHOW_BANK_1_RECALIBRATION_ENABLED:true"  \
"SHOW_BANK_1_VDDI_STATUS_ENABLED:true"  \
"SHOW_BANK_7_CALIB_STATUS_ENABLED:false"  \
"SHOW_BANK_7_RECALIBRATION_ENABLED:false"  \
"SHOW_BANK_7_VDDI_STATUS_ENABLED:false"  \
"SHOW_BANK_8_CALIB_STATUS_ENABLED:false"  \
"SHOW_BANK_8_RECALIBRATION_ENABLED:false"  \
"SHOW_BANK_8_VDDI_STATUS_ENABLED:false"  \
"SHOW_BANK_9_CALIB_STATUS_ENABLED:false"  \
"SHOW_BANK_9_RECALIBRATION_ENABLED:false"  \
"SHOW_BANK_9_VDDI_STATUS_ENABLED:false"  \
"SRAM_DELAY_INCR:3"  \
"SRAM_INIT_DONE_SIMULATION_DELAY:6"  \
"URAM_DELAY_INCR:3"  \
"USRAM_INIT_DONE_SIMULATION_DELAY:9"   }
# Exporting Component Description of PFSOC_INIT_MONITOR_C0 to TCL done
